# Generated by Django 5.1.5 on 2025-02-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
